### PR TITLE
🐟 mandrel drop in 🐟

### PR DESCRIPTION
**Pull request by eformat**
#### What is this PR About?
updates the graalvm jenkins agent to use the madrel drop in replacement
add in common tools (updated oc, helm, yq, yq)

supercedes/replaces - https://github.com/redhat-cop/containers-quickstarts/pull/429

#### How do we test this?
See Jenkinsfile test

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by pabrahamsson** [comment]
@eformat the PR build is failing and the fix is sitting in #441 so once that's been merged could you pull that into your branch and push again?

**Comment by eformat** [comment]
@pabrahamsson .. just pulled and merged in .. lets see it that works ...

git pull --no-ff https://github.com/pabrahamsson/containers-quickstarts.git jenkins-agent-conftest-build-fix

**Review by garethahealy — APPROVED** [review]

**Comment by garethahealy** [comment]
just needs a rebase (#441 is merged)

**Comment by eformat** [comment]
hiya @garethahealy .. waiting for @pabrahamsson review ... yeah?

Screenshot from 2021-02-17 19-04-07

**Review by pabrahamsson — APPROVED** [review]
Thank you @eformat LGTM

**Pull request merged**
