### PR TITLE
Publish jenkins-agent-image-mgmt to Quay.io and update to skopeo v1.1.1

### PR DESCRIPTION
**Pull request by pabrahamsson**
#### What is this PR About?
Publish jenkins-agent-image-mgmt to Quay.io and also update to skopeo v1.1.1.
Also added jenkins-agent-image-mgmt to the test suite

#### How do we test this?
Follow instructions in TESTING.md

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by pabrahamsson** [comment]
Thank you @garethahealy, could you also approve the PR? Prow comments alone isn't enough for this repo (plus you'll get Ninja points). Same for #405

**Review by garethahealy — APPROVED** [review]

**Pull request merged**
