### PR TITLE
Update ruby jenkins agent to nodejs 12

### PR DESCRIPTION
**Pull request by tom-stockwell**
#### What is this PR About?
Describe the contents of the PR

#### How do we test this?
Provide commands/steps to test this PR.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
maybe a test flake, will rerun to see if same error happens
- https://prow-default.apps.ci-1.cop.rht-labs.com/view/gcs/prow-artifacts-cop/pr-logs/pull/redhat-cop_containers-quickstarts/385/cq-jenkins-slaves-pr-build/1275765585652748288

/test cq-jenkins-slaves-pr-build

**Comment by tom-stockwell** [comment]
`ERROR: Error cloning remote repo 'origin'` - should be a flake

**Pull request merged**
