### PR TITLE
Add Erlang Jenkins slave, fixes #101

### LINKED ISSUE #101: Add Erlang Jenkins Slave and Erlang S2I image
# Overview
Add the ability for Jenkins to run a slave which can build Erlang applications using [Rebar3](https://www.rebar3.org/). Also, add an S2I image build which can convert an Erlang release to a runnable container image using Rebar3

# Acceptance criteria
* A new Jenkins slave image which has Rebar 3 and Erlang/OTP installed for use with creating a "release"
* A new S2I image which can take an Erlang release created via Rebar 3 and create a runnable container

### PR DESCRIPTION
**Pull request by pabrahamsson**
#### What is this PR About?
Adds an Erlang Jenkins slave

#### How do we test this?
See README in jenkins-slaves/jenkins-slave-erlang directory

cc: @redhat-cop/containerize-it

### CODE REVIEW

**Comment by pabrahamsson** [comment]
@InfoSec812 would you mind reviewing this PR?

**Comment by InfoSec812** [comment]
Working on testing everything on S9 now.

**Comment by InfoSec812** [comment]
@pabrahamsson I'm having issues getting the S2I image loaded up and wired in... How do I provision that?

**Comment by pabrahamsson** [comment]
@InfoSec812 the following steps should give you and s2i image and also build and deploy a simple erlang application.
1.  Clone my fork of this repo (or add as a remote)
2.  Check out the `feature/jenkins-slave-erlang` branch
3.  `cd s2i-erlang`
4.  `echo "SOURCE_REPOSITORY_REF=feature/jenkins-slave-erlang\nSOURCE_REPOSITORY_URL=https://github.com/pabrahamsson/containers-quickstarts" >> .openshift/params/application-bc`
5.  Follow steps in the README for using the applier to build and deploy
6.  You can change the Erlang application by also setting `APPLICATION_SOURCE_REPOSITORY_URL` and `APPLICATION_SOURCE_REPOSITORY_REF` in step 4 if you want to test something of your own.

**Comment by pabrahamsson** [comment]
@InfoSec812 did my directions above help you get unstuck?

**Comment by pabrahamsson** [comment]
@InfoSec812 any chance you are able to review this PR?

**Comment by InfoSec812** [comment]
Sorry for the long delay in reviewing this... I have tried both the CentOS and RHEL7 Jenkins slaves with good results using [THIS](https://github.com/InfoSec812/tcpserver) project. I could not however figure out how to get the release into the S2I image. I assume it needs to do `rebar3 release` and create the release in `_build`. Do I copy ALL of the deps or just the project dep (e.g. `_build/default/lib/idttcp/` or `_build/default/lib/idttcp/ebin/` or `_build/default/lib/`)?

**Comment by InfoSec812** [comment]
Looks like I might need to do:

```
rebar3 compile
rebar3 eunit
rebar3 release -d false
rebar3 as prod tar
```

Then I do an S2I build `--from-file` and point it at the tarball?

@pabrahamsson Can you confirm?

**Comment by garethahealy** [comment]
@pabrahamsson is this PR still current? or does it need updates, either to the PR or post PR, as i noticed it's all based on centos, does it need to be UBI'fied? 

Also, looking at the prow logs, the tests are failing with "FetchSourceFailed" - might be a good idea to tweak the _test/*.sh to show logs on failed builds as I couldnt see a way to view the jenkins logs from the prow output.

**Comment by garethahealy** [comment]
/test cq-jenkins-slaves-pr-build

looks like test flakes.

**Comment by pabrahamsson** [comment]
@garethahealy I've updated the jenkins piece of this PR to use UBI based image and a `Jenkinsfile.test`. Tests are now passing.
I'm considering ripping the s2i parts out of this PR as it seems that between @InfoSec812 and myself we don't have enough Erlang experience (this is my first) to get it sorted out.
Thoughts?

**Comment by garethahealy** [comment]
@pabrahamsson ; agreed. i've never done any erlang nor created an s2i base. i think the slave will be easy to maintain/understand, so i'd push the s2i bits onto another branch for the future, if anyone wants it.

**Comment by InfoSec812** [comment]
@garethahealy and @pabrahamsson The problem I keep running into with Erlang is that there are too many different possible build configurations. Is it using `rebar`, `rebar3`, `mix`, `make`? Who knows. We would have to add some pretty complex logic and lots of additional packages to the base image to cover all of the possible options. I'm OK if we remove Erlang support altogether until there is an actual demand.

**Comment by pabrahamsson** [comment]
@InfoSec812 I agree on the complexity with Erlang builds (which I'm also attributing to my lack of Erlang experience). This is also why I suggested to remove the S2I part of this PR.
I agree with @garethahealy that the Jenkins slave can be kept and easily updated with whatever tooling might be requested. Thoughts?

**Comment by InfoSec812** [comment]
@pabrahamsson Yeah, since I don't have any cycle to dedicate, I'm fine with this.

**Comment by pabrahamsson** [comment]
@garethahealy are you good to give your blessing?

**Pull request merged**
