### PR TITLE
Update jenkins agents to work on OCP v4.x, fixes #223, #224, #225

### LINKED ISSUE #223: Update jenkins-slave-python to work on OCP 4.x

### PR DESCRIPTION
**Pull request by pabrahamsson**
#### What is this PR About?
Some of our jenkins agents have dependencies which require a RHEL subscription.
With OCP 4.x moving to CoreOS worker nodes we can no longer use this model and should be leveraging Universal Base Images instead.

#### How do we test this?
```
./_test/setup.sh applier test-ubi ubi7 pabrahamsson/containers-quickstarts
./_test/setup.sh test test-ubi ubi7 pabrahamsson/containers-quickstarts
```
cc: @redhat-cop/day-in-the-life

Tested successfully in local OCP cluster as per instructions in [TESTING.md](/redhat-cop/containers-quickstarts/blob/master/TESTING.md).
```
$ ./_test/setup.sh applier pa-ubi ubi7 pabrahamsson/containers-quickstarts
...
localhost                  : ok=178  changed=12   unreachable=0    failed=0                                                    
                                                                                                                               
Wednesday 24 July 2019  16:32:52 -0400 (0:00:00.046)       0:01:17.378 ********                                                
===============================================================================                                                
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-zap' --- 2.6
6s                                                                                                                             
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-golang' --- 
1.86s                                                                                                                          
openshift-applier : Apply OpenShift objects based on template with params for 'test-pipelines : Deploy all test pipelines' --- 
1.71s                                                                                                                          
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-mongodb' ---
 1.71s                                                                                                                         
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-npm' --- 1.7
0s                                                                                                                             
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-ansible' ---
 1.62s                                                                                                                         
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-gradle' --- 
1.60s                                                                                                                          
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-arachni' ---
 1.55s                                                                                                                         
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-mvn' --- 1.4
7s                                                                                                                             
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-python' --- 
1.40s                                                                                                                          
Gathering Facts -------------------------------------------------------------------------------------------------------- 1.20s 
openshift-applier : Create OpenShift objects based on template with params for 'Environment Setup : Create Projects' --- 1.14s 
openshift-applier : Retrieve oc client version ------------------------------------------------------------------------- 1.10s 
openshift-applier : Change 'params_from_vars' fact (if applicable) into command line parameters ------------------------ 0.41s 
openshift-applier : Create/Apply OpenShift Cluster Content ('jenkins-slave-nodes') - based on individual files --------- 0.40s 
openshift-applier : Create OpenShift objects --------------------------------------------------------------------------- 0.37s 
openshift-applier : Change 'params_from_vars' fact (if applicable) into command line parameters ------------------------ 0.36s 
openshift-applier : Determine location for the file -------------------------------------------------------------------- 0.36s 
openshift-applier : Determine location for the file -------------------------------------------------------------------- 0.35s 
openshift-applier : Copy inventory file to remote ---------------------------------------------------------------------- 0.32s
$ 
$ ./_test/setup.sh test pa-ubi ubi7 pabrahamsson/containers-quickstarts
Ensure all Builds are executed...
build.build.openshift.io/jenkins-slave-golang-pipeline-1 started
Waiting for all builds to start...
Waiting for all builds to complete...
Check to see how many builds Failed
Tests Completed Successfully!
```

### CODE REVIEW

**Comment by pabrahamsson** [comment]
Let's get  started on using UBI for our Jenkins Agents. This is a first stab that let's us build these on OCP 4.x but I'm sure there's room for improvement.

**Comment by etsauer** [comment]
@pabrahamsson looks like the CI failed because several of the images failed to build. can you look into why?

**Comment by pabrahamsson** [comment]
@etsauer AFAICT these failures are unrelated to the changes made here and are pre-existent to the CI testing implementation. Based on the conversation in #226 I'll see if I can't fix these failures as part of this PR.

**Comment by pabrahamsson** [comment]
Tested successfully in local OCP cluster as per instructions in [Testing.md](/redhat-cop/containers-quickstarts/blob/master/TESTING.md).
```
$ ./_test/setup.sh applier pa-ubi7 pabrahamsson/containers-quickstarts
...
localhost                  : ok=178  changed=12   unreachable=0    failed=0                                                    
                                                                                                                               
Wednesday 24 July 2019  16:32:52 -0400 (0:00:00.046)       0:01:17.378 ********                                                
===============================================================================                                                
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-zap' --- 2.6
6s                                                                                                                             
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-golang' --- 
1.86s                                                                                                                          
openshift-applier : Apply OpenShift objects based on template with params for 'test-pipelines : Deploy all test pipelines' --- 
1.71s                                                                                                                          
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-mongodb' ---
 1.71s                                                                                                                         
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-npm' --- 1.7
0s                                                                                                                             
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-ansible' ---
 1.62s                                                                                                                         
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-gradle' --- 
1.60s                                                                                                                          
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-arachni' ---
 1.55s                                                                                                                         
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-mvn' --- 1.4
7s                                                                                                                             
openshift-applier : Apply OpenShift objects based on template with params for 'jenkins-slave-nodes : jenkins-slave-python' --- 
1.40s                                                                                                                          
Gathering Facts -------------------------------------------------------------------------------------------------------- 1.20s 
openshift-applier : Create OpenShift objects based on template with params for 'Environment Setup : Create Projects' --- 1.14s 
openshift-applier : Retrieve oc client version ------------------------------------------------------------------------- 1.10s 
openshift-applier : Change 'params_from_vars' fact (if applicable) into command line parameters ------------------------ 0.41s 
openshift-applier : Create/Apply OpenShift Cluster Content ('jenkins-slave-nodes') - based on individual files --------- 0.40s 
openshift-applier : Create OpenShift objects --------------------------------------------------------------------------- 0.37s 
openshift-applier : Change 'params_from_vars' fact (if applicable) into command line parameters ------------------------ 0.36s 
openshift-applier : Determine location for the file -------------------------------------------------------------------- 0.36s 
openshift-applier : Determine location for the file -------------------------------------------------------------------- 0.35s 
openshift-applier : Copy inventory file to remote ---------------------------------------------------------------------- 0.32s
$ 
$ ./_test/setup.sh test pa-ubi ubi7 pabrahamsson/containers-quickstarts
Ensure all Builds are executed...
build.build.openshift.io/jenkins-slave-golang-pipeline-1 started
Waiting for all builds to start...
Waiting for all builds to complete...
Check to see how many builds Failed
Tests Completed Successfully!
```

**Comment by etsauer** [comment]
@pabrahamsson the test output that you show doesn't look right. It should output a list of builds that completed. I'm thinking that it might not be consistently looking in the right namepsace.

**Comment by etsauer** [comment]
@pabrahamsson I just ran the tests in an openshift 4 cluster, and here's what I see:

```
$ oc get builds --all-namespaces
NAMESPACE   NAME                              TYPE              FROM                                      STATUS                       STARTED              DURATION
pa-ubi7     jenkins-slave-ansible-1           Docker            Git@pabrahamsson/containers-quickstarts   Failed (FetchSourceFailed)   About a minute ago   10s
pa-ubi7     jenkins-slave-arachni-1           Docker            Git@pabrahamsson/containers-quickstarts   Failed (FetchSourceFailed)   About a minute ago   9s
pa-ubi7     jenkins-slave-golang-1            Docker            Git@pabrahamsson/containers-quickstarts   Failed (FetchSourceFailed)   About a minute ago   9s
pa-ubi7     jenkins-slave-gradle-1            Docker            Git@pabrahamsson/containers-quickstarts   Failed (FetchSourceFailed)   About a minute ago   14s
pa-ubi7     jenkins-slave-mongodb-1           Docker            Git@pabrahamsson/containers-quickstarts   Failed (FetchSourceFailed)   About a minute ago   10s
pa-ubi7     jenkins-slave-mvn-1               Docker            Git@pabrahamsson/containers-quickstarts   Failed (FetchSourceFailed)   About a minute ago   14s
pa-ubi7     jenkins-slave-npm-1               Docker            Git@pabrahamsson/containers-quickstarts   Failed (FetchSourceFailed)   About a minute ago   14s
pa-ubi7     jenkins-slave-python-1            Docker            Git@pabrahamsson/containers-quickstarts   Failed (FetchSourceFailed)   About a minute ago   14s
pa-ubi7     jenkins-slave-zap-1               Docker            Git@pabrahamsson/containers-quickstarts   Failed (FetchSourceFailed)   About a minute ago   14s
pa-ubi7     jenkins-slave-golang-pipeline-1   JenkinsPipeline   Git@pabrahamsson/containers-quickstarts   New                                               
```

That last one looks like it might be because openshift 4 doesn't auto-create a Jenkins server like 3 does. we should open an issue for that. 

The real issue is that you are missing in argument to the test script. It should be:

```
$ ./_test/setup.sh applier pa-ubi7 ubi7 pabrahamsson/containers-quickstarts
$ ./_test/setup.sh test pa-ubi7 ubi7 pabrahamsson/containers-quickstarts
```

**Comment by etsauer** [comment]
@pabrahamsson FYI, I've opened https://github.com/redhat-cop/containers-quickstarts/pull/233 to help keep this from happening.

**Comment by etsauer** [comment]
@pabrahamsson after getting the tests pointed at the right namespace, it looks like a few of them are failing:

```
Ensure all Builds are executed...
build.build.openshift.io/jenkins-slave-golang-pipeline-1 started
Waiting for all builds to start...
Waiting for all builds to complete...
Check to see how many builds Failed
Some builds failed. Printing Report
NAME                              TYPE              FROM   STATUS     REASON
jenkins-slave-ansible-1           Docker            Git    Failed     DockerBuildFailed
jenkins-slave-arachni-1           Docker            Git    Complete   <none>
jenkins-slave-golang-1            Docker            Git    Complete   <none>
jenkins-slave-golang-pipeline-1   JenkinsPipeline   Git    Complete   <none>
jenkins-slave-gradle-1            Docker            Git    Complete   <none>
jenkins-slave-mongodb-1           Docker            Git    Failed     DockerBuildFailed
jenkins-slave-mvn-1               Docker            Git    Complete   <none>
jenkins-slave-npm-1               Docker            Git    Failed     InvalidContextDirectory
jenkins-slave-python-1            Docker            Git    Failed     DockerBuildFailed
jenkins-slave-zap-1               Docker            Git    Failed     GenericBuildFailed
```

**Comment by pabrahamsson** [comment]
Thank you for taking a look @etsauer, I had a typo in my instructions as you correctly pointed out (I've updated above).
However, I'm not getting any issues when running this in d2 (with pipeline-tests commented out). I don't have access to a v4 cluster that I can test this on.
```
$ ./_test/setup.sh applier pa-ubi ubi7 pabrahamsson/containers-quickstarts
$ ./_test/setup.sh test pa-ubi ubi7 pabrahamsson/containers-quickstarts
Ensure all Builds are executed...
Waiting for all builds to start...
Waiting for all builds to complete...
Check to see how many builds Failed
Tests Completed Successfully!
$ oc get build -n pa-ubi
NAME                      TYPE      FROM          STATUS     STARTED         DURATION
jenkins-slave-ansible-1   Docker    Git@8d0ee8e   Complete   7 minutes ago   7s
jenkins-slave-arachni-1   Docker    Git@8d0ee8e   Complete   6 minutes ago   35s
jenkins-slave-golang-1    Docker    Git@8d0ee8e   Complete   6 minutes ago   52s
jenkins-slave-gradle-1    Docker    Git@8d0ee8e   Complete   6 minutes ago   20s
jenkins-slave-mongodb-1   Docker    Git@8d0ee8e   Complete   5 minutes ago   42s
jenkins-slave-mvn-1       Docker    Git@8d0ee8e   Complete   5 minutes ago   8s
jenkins-slave-npm-1       Docker    Git@8d0ee8e   Complete   5 minutes ago   44s
jenkins-slave-python-1    Docker    Git@8d0ee8e   Complete   5 minutes ago   28s
jenkins-slave-zap-1       Docker    Git@8d0ee8e   Complete   5 minutes ago   9s
```

**Comment by etsauer** [comment]
@pabrahamsson can you rebase and resolve conflicts so we can merge this? The tests look good.

**Comment by garethahealy** [comment]
I believe this PR has broken the ansible slave. As SCL is used for python3, its never enabled when the contain is running via:
-  jenkins-slaves/jenkins-slave-ansible/scl_enable

Which means python2.7 is the default, which causes ansible command not found errors

**Pull request merged**
