### PR TITLE
🦩bump version to latest argocd-1.6.0🦩

### PR DESCRIPTION
**Pull request by eformat**
#### What is this PR About?
Describe the contents of the PR

#### How do we test this?
Provide commands/steps to test this PR.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
@pabrahamsson ; what causes the _needs-ok-to-test_ label to be added? I would have thought if a change affects the Jenkins slaves -  which has the prow job attached - the tests would auto-trigger, but that didn't happen.

**Comment by pabrahamsson** [comment]
> @pabrahamsson ; what causes the _needs-ok-to-test_ label to be added? I would have thought if a change affects the Jenkins slaves - which has the prow job attached - the tests would auto-trigger, but that didn't happen.

I believe sure this happens when the committer isn't part of the `redhat-cop` org. 

So @eformat you might want to open an issue over at [redhat-cop/org](/redhat-cop/org/issues/new/choose) to become a new contributor. This is obviously not a requirement but more of a convenience.

**Pull request merged**
