### PR TITLE
🦩 jenkins-agent-graalvm - updates for latest version 🦩

### PR DESCRIPTION
**Pull request by eformat**
#### What is this PR About?
Updates for latest versions:
- Mandrel/Graal - GRAAL_VERSION=20.3.3.0-Final
- Helm - HELM_VERSION=3.6.3
- oc OC_VERSION=4.8.2
- yq - YQ_VERSION=4.11.2

#### How do we test this?
see test in this repo

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
not sure why it failed (prow seems down currently as well)

/test cq-jenkins-agents-pr-build

**Comment by eformat** [comment]
odd. this builds locally fine .. investigating ...

**Comment by eformat** [comment]
OK .. that fixed it .. oddly this installed ok locally @garethahealy ..

**Review by garethahealy — APPROVED** [review]

**Pull request merged**
