### PR TITLE
RABBITMQ: Set proper locale env vars

### LINKED ISSUE #490: RabbitMQ liveness probe is failing due to incorrect locale setting
```bash
Status of node rabbit@rabbitmq-2.rabbitmq.rabbitmq-acceptance-4utqy.svc.cluster.local ...
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```
This causes the liveness probe to fail and pods are being restarted

### PR DESCRIPTION
**Pull request by pabrahamsson**
#### What is this PR About?
Resolves #490 

#### How do we test this?
The automated CI test is expected to fail, use the below for testing.
```
git clone -b issue-490 https://github.com/pabrahamsson/containers-quickstarts
cd containers-quickstarts
bats rabbitmq/test/acceptance
```

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by pabrahamsson** [comment]
@garethahealy can you PTAL when get a chance?

**Review by garethahealy — APPROVED** [review]

**Pull request merged**
