### PR TITLE
🦆 FIX - Jenkins slave npm chrome dep 🦆

### PR DESCRIPTION
**Pull request by springdo**
#### What is this PR About?
As per discussion with @oybed and @pabrahamsson  - I've removed the `ADD` in favour of `curl` to bring in the Chrome Browser 

#### How do we test this?
`docker build -t name/jenkins-slave-npm .`

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
@springdo ; instead of curl'ing, can we use chromium? it's part of the RH yum repos

**Comment by springdo** [comment]
The rhel image Dockerfile uses a proper repo for chrome, but yeah if there was one for centos using chromium we could swap to it?

**Comment by pabrahamsson** [comment]
@springdo @garethahealy ideally we'd like to use one of the upstream [UBI based jenkins images](https://quay.io/openshift/origin-jenkins-agent-base) but I know having to include a browser makes that challenging.

**Comment by garethahealy** [comment]
It's in epel (if my memory is correct) - so you don't have to include other yum repos, i.e.: the google one which says they don't support RHEL

**Pull request merged**
