### PR TITLE
Added Helm 3 chart for Jenkins on OpenShift

### PR DESCRIPTION
**Pull request by InfoSec812**
#### What is this PR About?
Adds a Helm 3 Chart for deploying Jenkins on OpenShift

Resolves: #395 

#### How do we test this?
```
git clone <repo>
cd <repo>/jenkins-helm3
helm template jenkins ${PWD}
```

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by tylerauerbeck** [comment]
@InfoSec812 We're currently working on moving the rht-labs/charts repo into the CoP, which has a Jenkins chart as well. We should take a look to see if there is any delta between the two and then get that merged in there. I'll check to see where we are in the migration process and then see if we can get this moved there if that's alright?

**Comment by InfoSec812** [comment]
@tylerauerbeck Looking at the Labs Chart for Jenkins, I think that this is pretty specific to the Labs way of doing things. I think we'll want to use some logic to allow different installation paths/configs/options... For example, SealedSecrets...

**Comment by springdo** [comment]
Hi @InfoSec812 that sounds great but perhaps there is a way we can add those config specific versions in such a way that both the labs and cop approaches are maintained from one single source. As we all know, there are about 8 different ways across cop repos to install Jenkins right now from templates .... Would love to not be in same position with the helm approaches!

BTW, Jenkins in the labs space does support sealed secrets at the moment if you want to try it out!

**Comment by InfoSec812** [comment]
@springdo My point in the comment is that I **CANNOT** use SealedSecrets in the deployment environments I am targeting right now. Which is why the Jenkins Chart needs to be a little *less* opinionated (or at least more flexible).

**Comment by springdo** [comment]
Hey Deven! The rht-labs helm-charts repository has moved across to the cop-org, do you want some help to create a values file to match your implementation here or how do you want to proceed?

**Comment by pabrahamsson** [comment]
@InfoSec812 @tylerauerbeck @springdo can we try and figure out where we want to go with this? I agree that having multiple Helm charts for Jenkins isn't ideal, will this [Jenkins Helm chart](https://github.com/redhat-cop/helm-charts/tree/master/charts/jenkins) work for your use case @InfoSec812?

**Pull request closed without merging**
