### PR TITLE
Added github workflow action for conftest

### PR DESCRIPTION
**Pull request by garethahealy**
#### What does this PR do?
Adds conftest as a github workflow action

#### How should this be tested?
See actions output

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
Requires following PR before merging:
- https://github.com/redhat-cop/github-actions/pull/7

helm tests are currently disabled, as the action doesn't include helm yet - need to do another PR.

**Comment by pabrahamsson** [comment]
> Requires following PR before merging:
> 
> * [redhat-cop/github-actions#7](https://github.com/redhat-cop/github-actions/pull/7)
> 
I've merged this and re-ran the test here, I'd like your feedback on the the errors before continuing.

> helm tests are currently disabled, as the action doesn't include helm yet - need to do another PR.

**Comment by garethahealy** [comment]
@pabrahamsson ; what errors? this all looks green:
- https://github.com/redhat-cop/containers-quickstarts/pull/354/checks?check_run_id=721676937

**Comment by pabrahamsson** [comment]
> @pabrahamsson ; what errors? this all looks green:
> 
> * https://github.com/redhat-cop/containers-quickstarts/pull/354/checks?check_run_id=721676937

This is the job that I re-ran after merging https://github.com/redhat-cop/github-actions/pull/7
https://github.com/redhat-cop/containers-quickstarts/runs/721534769?check_suite_focus=true

It is passing now (and has for the last few runs) so I think we're good.

**Pull request merged**
