### PR TITLE
Updated to oc 4.3 client

### PR DESCRIPTION
**Pull request by huddlesj**
Updated OC client for issue #276 

#### What is this PR About?
Updated oc client in default Docker file. Also as example added an OC3 only and a oc3/oc4 Dockerfile

#### How do we test this?
Provide commands/steps to test this PR.

Use oc client to connect to Openshift 4 cluster and oc3 client to connect to an Openshift 3 cluster.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
is this needed? shouldn't the 4.3 client be backwards compatible with 3.11?

**Comment by huddlesj** [comment]
@garethahealy I wasn't sure if we could get rid of the 3 client or if we would need to maintain it in a separate tag, branch or release. If it is not needed I can git rid of the oc3 and the multi Docker files.

**Comment by etsauer** [comment]
@huddlesj @garethahealy yeah, I think we can remove these new images. we have older tags available on quay that will still have the 3.11 oc version if people need it. https://quay.io/repository/redhat-cop/tool-box?tab=tags

**Comment by pabrahamsson** [comment]
Still WIP @huddlesj? Or are we good to merge?

**Comment by huddlesj** [comment]
@pabrahamsson Yes, We are good to merge.

**Pull request merged**
