### PR TITLE
Add Jenkins Arachni agent to CI

### PR DESCRIPTION
**Pull request by pabrahamsson**
#### What is this PR About?
Describe the contents of the PR

#### How do we test this?
Provide commands/steps to test this PR.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by pabrahamsson** [comment]
@etsauer or @garethahealy would you be able to review this one? It has been sitting for a while and should be pretty straightforward.

**Comment by garethahealy** [comment]
@pabrahamsson ; latest failure seems like a connection issue - i know GH has been having some issues today. maybe related?

**Comment by garethahealy** [comment]
@pabrahamsson ; i can run the failing command locally. any ideas?

**Comment by garethahealy** [comment]
@pabrahamsson ; you OK to fix conflict?

**Pull request merged**
