### PR TITLE
add github workflows for gitlab-runners/ubi7-gitlab-runner and update github workflow for gitlab-runners/ubi8-git 

### PR DESCRIPTION
**Pull request by itewk**
#### What is this PR About?
* add github workflows for gitlab-runners/ubi7-gitlab-runner
* update github workflow for gitlab-runners/ubi8-git

#### How do we test this?
The workflow will run.

You can see example runs against my own fork:
https://github.com/itewk/containers-quickstarts/actions

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by itewk** [comment]
@pabrahamsson starting to expand upon https://github.com/redhat-cop/containers-quickstarts/pull/323

**Comment by itewk** [comment]
@pabrahamsson does the quay.io service account configurted for the repo have permissions to create new repos? otherwise someone with access needs to manually create the new repo in quay.io otherwise the publish job will fail on merge.

**Comment by pabrahamsson** [comment]
> @pabrahamsson does the quay.io service account configurted for the repo have permissions to create new repos (which i havn't actually found a way to do)? otherwise someone with access needs to manually create the new repo in quay.io otherwise the publish job will fail on merge.

My bad, to quick on the merge. I'll create it.

**Comment by itewk** [comment]
> > @pabrahamsson does the quay.io service account configurted for the repo have permissions to create new repos (which i havn't actually found a way to do)? otherwise someone with access needs to manually create the new repo in quay.io otherwise the publish job will fail on merge.
> 
> My bad, to quick on the merge. I'll create it.

Don't forget to update the robo account to have `write` permissions to the new repo.

**Comment by itewk** [comment]
and it looks like you didn't hit the `merge` button yet, so saved :)

**Comment by pabrahamsson** [comment]
> and it looks like you didn't hit the `merge` button yet, so saved :)

The `/lgtm` should've merged it.
Anyway, the Quay repo has been created and the robo account has write access.

**Pull request merged**
