### PR TITLE
ubi8-git and ubi8-google-api-python-client - init add

### PR DESCRIPTION
**Pull request by itewk**
#### What is this PR About?
Adds two utility images useful for use in GitLab CI pipelines, but could be used in other places to.

#### How do we test this?
You could build the docker image and run it if you like. We are using these images in an internal pipeline at the moment but thought it best to share them with the world.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by itewk** [comment]
@etsauer would appreciate your review and merge here. trying to upstream some stuff we are using internally. with hopes of getting it into quay.io/redhat-cop.

**Comment by itewk** [comment]
@pabrahamsson could i get you to look at this one too, its same idea as https://github.com/redhat-cop/containers-quickstarts/pull/309

**Comment by itewk** [comment]
@pabrahamsson looks like it needs a `lgtm` from you to merge.

**Comment by pabrahamsson** [comment]
It does @itewk but I need a bit more time on this one before I'm ready with the `lgtm`

**Comment by itewk** [comment]
kk.

**Comment by itewk** [comment]
@pabrahamsson okay. if we come up with any more images used for gitlab runners we will make a a parrent folder for them.

**Comment by itewk** [comment]
@pabrahamsson does something special have to happen to have these images built and pushed to https://quay.io/organization/redhat-cop?

**Comment by pabrahamsson** [comment]
AFAIK know it is not something that happens by default. I'm finding out what the process is to have this done.

**Comment by pabrahamsson** [comment]
@itewk turns out the process to build images from a monorepo (such as this one) doesn't really exist. I started some work to make this possible (through GH actions) that I hope to have available shortly (currently in review).

**Comment by itewk** [comment]
@pabrahamsson i thought for sure @etsauer had it set up to build and push the images automatically to quay.io/redhat-cop. I remember the “automagic” for the Jenkins workers images being busted at one point and he fixed it.

**Comment by etsauer** [comment]
@itewk you're right, we did, but it was all set up in builds on the quay side that I was having to manually couch sound the quay ui to set up for each image. We wanted to switch to something more templated and repeatable using GitHub workflows that contributors could implement themselves.

**Comment by itewk** [comment]
@etsauer anything can do to help? not sure how github workflows work, but if its anything like Gitlab CI and you need a semi stable OCP cluster to run things on....i may have one of those.

in the mean time while the "automatic" gets figured out, is there a manual way we could get these images and the one from https://github.com/redhat-cop/containers-quickstarts/pull/309 built and pushed to the quay.io/redhat-cop space?

**Pull request merged**
