### PR TITLE
🐛Bump Helm Version in the jenkins slave 🐛

### PR DESCRIPTION
**Pull request by springdo**
#### What is this PR About?
Bump Helm Version in the jenkins slave

#### How do we test this?
Clone it, build it, use it #JENKINSFORLIFE !!!

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by springdo** [comment]
Congrats @etsauer - you've been randomly selected to hit approve 👍 

/assign @etsauer

**Comment by tylerauerbeck** [comment]
:see_no_evil: Figuring out prow, nothing to see here :see_no_evil: 

/assign @tylerauerbeck

**Comment by tylerauerbeck** [comment]
@pabrahamsson Am I missing some magic here?

**Comment by garethahealy** [comment]
@tylerauerbeck ; you not on the approver's list:
- https://github.com/redhat-cop/containers-quickstarts/blob/master/OWNERS

but you can give it an lgtm

**Comment by tylerauerbeck** [comment]
@garethahealy Ahh, that makes sense.

/lgtm

**Comment by springdo** [comment]
@garethahealy  - the ci is failing cuz of a missing gradle slave test.... is this borked?

**Comment by garethahealy** [comment]
@springdo ; not sure why it's complaining, as I can see the file:
- https://github.com/redhat-cop/containers-quickstarts/blob/master/jenkins-slaves/jenkins-slave-gradle/Jenkinsfile.test

does your branch include said file? or does it need a rebase?

**Comment by springdo** [comment]
@garethahealy - yeah I see that, i've pulled in latest master here so should be able to 
/test cq-jenkins-slaves-pr-build

**Pull request merged**
