### PR TITLE
Add OWNERS file

### PR DESCRIPTION
**Pull request by pabrahamsson**
#### What is this PR About?
Add OWNERS file (see [documentation](https://go.k8s.io/owners)) to leverage Prow plugins

#### How do we test this?
Provide commands/steps to test this PR.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by pabrahamsson** [comment]
@etsauer yes we can as long as this comment in the [documentation](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners_aliases) isn't a concern for us.
>We use aliases for groups instead of GitHub Teams, because changes to GitHub Teams are not publicly auditable.

**Comment by etsauer** [comment]
@pabrahamsson hmm, i guess i don't know what a "group" is then. I thought they were the same thing. @sabre1041 ?

**Comment by pabrahamsson** [comment]
@etsauer I think what they're saying is that they create their own "groups" in the `OWNERS_ALIASES` file instead of using GH teams.

**Comment by sabre1041** [comment]
@etsauer @pabrahamsson it depends. There needs to be an understanding that groups are distinct from GH teams and that they would need to be managed separately

**Comment by etsauer** [comment]
@sabre1041 but that's what I am trying to understand... HOW do you manage a group? I don't know what that is, or how its different from a team.

**Comment by pabrahamsson** [comment]
My understanding of a group (`core-group`):
```
aliases:
  core-group:
    - user1
    - user2
```
This is managed by the `OWNERS_ALIASES` file and you/we need to manually update it through PRs.
The `core-group` can now be used in `OWNERS` files in the repo.

**Comment by sabre1041** [comment]
@etsauer groups are a prow convention that is managed through files within the repository where as teams are a GitHub convention

**Comment by pabrahamsson** [comment]
@etsauer @sabre1041 are we good as is? We can always explore using GH teams and/or `OWNERS_ALIASES` down the road.

**Comment by etsauer** [comment]
@pabrahamsson yeah, i'm good with it. Let's merge and address it when it becomes a problem.

**Pull request merged**
