### PR TITLE
WIP: add github workflows for gitlab-runners/ubi8-asciidoctor

### PR DESCRIPTION
**Pull request by itewk**
### WARNING
Before merging be sure to create the following repos:

* `quay.io/redhat-cop/gitlab-runners-ubi8-asciidoctor`

### What is this PR About?
* add github workflows for gitlab-runners/ubi8-asciidoctor
* gitlab-runners/ubi8-asciidoctor/Dockerfile - remove duplicate git install

#### How do we test this?
You can see https://github.com/itewk/containers-quickstarts/actions for example of workflows running.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by itewk** [comment]
# WARNING #

Before merging be sure to create the following repos:

    quay.io/redhat-cop/gitlab-runners-ubi8-asciidoctor

**Comment by itewk** [comment]
@buuhsmead FYI, this will make it so the asciidoctor image gets published to quay.io/redhat-cop/gitlab-runners-ubi8-asciidoctor

**Comment by itewk** [comment]
though now that i think about it the ubi8-git and ubi8-asciidocotor images arn't gitlab runner specific at all....so probalby they shouldn't be in this folder....a different MR to fix that maybe?

**Comment by itewk** [comment]
@pabrahamsson or maybe shoudl fix the pathing on this image before pushing to quay.io....

**Comment by buuhsmead** [comment]
Not sure what you are doing with this image. Also not sure if adding gitlab-runners-code to this image will render it specific to gitlab. And not usable for plain podman (docker) runs anymore.

**Comment by itewk** [comment]
@buuhsmead  didn't add any gitlab-runner specific code, but when i reorganized images in a different MR i accidnetly without thinking group them all under a gitlab-runners folder since that was the contexct they were getting used in. really this and the ubi8-git image should just be moved to a "utils" folder.....sigh. another refactor

**Comment by itewk** [comment]
replaced by https://github.com/redhat-cop/containers-quickstarts/pull/331

**Pull request closed without merging**
