### PR TITLE
Update cluster-lifecycle -> openshift-templates

### PR DESCRIPTION
**Pull request by tylerauerbeck**
#### What is this PR About?
Changes in inventory to point to the new project request template location in openshift-templates

#### How do we test this?
Deploy any of the apps as expected using the new location

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by pabrahamsson** [comment]
Is this still WIP @tylerauerbeck?

**Comment by tylerauerbeck** [comment]
@pabrahamsson This should be in better shape now. Feel free to take a look when you're ready.

**Comment by etsauer** [comment]
@tylerauerbeck can you resolve the conflicts in your branch please?

**Comment by pabrahamsson** [comment]
@tylerauerbeck any chance you can rebase your branch?

**Comment by pabrahamsson** [comment]
ping @tylerauerbeck

**Comment by tylerauerbeck** [comment]
@pabrahamsson This should be ready for review.

**Pull request merged**
