### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by adynetro**
add curl to image 

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Review by pabrahamsson — COMMENTED** [review]
Thank you @adynetro, can you give some context around why curl is needed in this image?

**Comment by adynetro** [comment]
curl is not present in version greather than 8.1 and installplugin.sh fails @pabrahamsson

**Review by pabrahamsson — APPROVED** [review]
/lgtm

**Pull request merged**
