### PR TITLE
removed eap chart

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
https://github.com/redhat-cop/containers-quickstarts/issues/472

PR to add eap upstream example into helm repo:
- https://github.com/redhat-cop/helm-charts/pull/142

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Review by pabrahamsson — DISMISSED** [review]
/lgtm

**Comment by garethahealy** [comment]
@pabrahamsson ; fixed conflicts, needs another lgtm

**Review by pabrahamsson — APPROVED** [review]
/lgtm

**Pull request merged**
