### PR TITLE
Adding GoWS s2i image

### PR DESCRIPTION
**Pull request by etsauer**
#### What is this PR About?
Describe the contents of the PR

#### How do we test this?

```
oc new-build https://github.com/etsauer/containers-quickstarts.git#s2i-gows --context-dir=s2i-gows --strategy=docker --name=s2i-gows
oc new-app s2i-gows~https://github.com/etsauer/containers-quickstarts.git#s2i-gows --context-dir=s2i-gows/test-site --name=gows-test
```
cc: @redhat-cop/containerize-it

### CODE REVIEW

**Comment by sabre1041** [comment]
@etsauer can you verify the 2nd command to execute

**Comment by etsauer** [comment]
@sabre1041 yes, i just updated it.

**Comment by sabre1041** [comment]
@etsauer verified the content. Needed to add a step to expose a route

```
oc expose svc gows-test
```

Do we want to also add a README to align with the other quickstarts?

**Comment by etsauer** [comment]
@sabre1041 done.

**Comment by sabre1041** [comment]
@redhat-cop/cant-contain-this anyone else want to take a look at this?

**Pull request merged**
