### PR TITLE
🦀 fix static linking issue native mode 🦀

### PR DESCRIPTION
**Pull request by eformat**
#### What is this PR About?
see https://quarkus.io/guides/building-native-image#configuring-c-development

fix static linking issue:

[maven-run : mvn-goals] Based on the linker command output, possible reasons for this include:
[maven-run : mvn-goals] 1. It appears as though libstdc++.a is missing. Please install it.

[maven-run : mvn-goals] /usr/bin/ld: cannot find -lstdc++
[maven-run : mvn-goals] collect2: error: ld returned 1 exit status

#### How do we test this?
run quarkus compile using "mvn -s package -Dnative" you should get static linked binary created

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
Can build this locally - not sure why CI is failing. @pabrahamsson ; can you see the logs?

```
$ docker build . -t graal-agent
[+] Building 147.9s (9/9) FINISHED
```

**Review by garethahealy — APPROVED** [review]

**Comment by pabrahamsson** [comment]
> Can build this locally - not sure why CI is failing. @pabrahamsson ; can you see the logs?
> 
> ```
> $ docker build . -t graal-agent
> [+] Building 147.9s (9/9) FINISHED
> ```

@garethahealy @eformat the logs are available here: https://prow-prow.apps.ci-1.cop.rht-labs.com/log?job=cq-jenkins-agents-pr-build&id=1374633849757110272
I need to look into why the job isn't linked from here.

It looks like @eformat is on a branch that's behind upstream master and doesn't have #457 which fixes the above issue.

**Comment by eformat** [comment]
@garethahealy @pabrahamsson .. have merged master into here and re-pushed, should fix it ...

https://github.com/redhat-cop/containers-quickstarts/pull/460/commits/31e7e304b47821403ca02d9780eb9829175ee613

**Review by pabrahamsson — APPROVED** [review]
/lgtm

**Pull request merged**
