### PR TITLE
s2i-httpd image

### PR DESCRIPTION
**Pull request by sabre1041**
#### What does this PR do?

Adding Source to Image support for a standalone Apache HTTPD web server
#### How should this be manually tested?

Execute the instructions found in the s2i-httpd README
#### Is there a relevant Issue open for this?

https://trello.com/c/jMcYQV7t
#### Who would you like to review this?

/cc @etsauer @raffaelespazzoli

### CODE REVIEW

**Comment by sabre1041** [comment]
bump @etsauer @raffaelespazzoli

**Comment by etsauer** [comment]
@sabre1041 problem during build from template:

```
[esauer@localhost containers-quickstarts]$ oc create -f quickstart-templates/rhel-templates.json 
template "play-framework-quickstart-rhel" created
template "java-quickstart-rhel" created
template "httpd-quickstart-rhel" created
[esauer@localhost containers-quickstarts]$ oc new-app --template=httpd-quickstart-rhel
--> Deploying template httpd-quickstart-rhel

     httpd-quickstart-rhel
     ---------
     HTTPD builder and sample application

     * With parameters:
        * Apache HTTPD builder name=s2i-httpd
        * HTTPD builder source url=https://github.com/redhat-cop/containers-quickstarts.git
        * HTTPD source branch/tag reference.=master
        * HTTPD builder context directory.=s2i-httpd
        * Apache application name=httpd-app
        * HTTPD application source url=https://github.com/sclorg/httpd-container.git
        * HTTPD application source branch/tag reference.=master
        * HTTPD application context directory.=2.4/test/sample-test-app
        * HTTPD application route hostname.=

--> Creating resources with label app=httpd-quickstart-rhel ...
    imagestream "sclorg-httpd-container" created
    imagestream "s2i-httpd" created
    imagestream "httpd-app" created
    buildconfig "s2i-httpd" created
    route "httpd-app" created
    buildconfig "httpd-app" created
    service "httpd-app" created
    deploymentconfig "httpd-app" created
--> Success
    Build scheduled, use 'oc logs -f bc/s2i-httpd' to track its progress.
    Build scheduled, use 'oc logs -f bc/httpd-app' to track its progress.
    Run 'oc status' to view your app.
[esauer@localhost containers-quickstarts]$ oc get pods
NAME                READY     STATUS    RESTARTS   AGE
s2i-httpd-1-build   0/1       Error     0          24s
[esauer@localhost containers-quickstarts]$ oc logs build/s2i-httpd-1
Cloning "https://github.com/redhat-cop/containers-quickstarts.git" ...
	Commit:	329f59a9788e1deea13ead64003bbc90dfaa7c8d (Merge pull request #8 from sabre1041/s2i-java-bom)
	Author:	Eric Sauer <etsauer@gmail.com>
	Date:	Thu Nov 17 10:52:20 2016 -0500
error: build error: open /tmp/docker-build305617422/s2i-httpd/Dockerfile: no such file or directory
[esauer@localhost containers-quickstarts]$ 
```

**Comment by etsauer** [comment]
@sabre1041 problem during build:

```
[esauer@localhost containers-quickstarts]$ oc new-project httpd-demo
Already on project "httpd-demo" on server "https://master-0.rdu-demo.casl.rht-labs.com:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.
[esauer@localhost containers-quickstarts]$ oc create -f quickstart-templates/rhel-templates.json 
template "play-framework-quickstart-rhel" created
template "java-quickstart-rhel" created
template "httpd-quickstart-rhel" created
[esauer@localhost containers-quickstarts]$ oc new-app --template=httpd-quickstart-rhel
--> Deploying template httpd-quickstart-rhel

     httpd-quickstart-rhel
     ---------
     HTTPD builder and sample application

     * With parameters:
        * Apache HTTPD builder name=s2i-httpd
        * HTTPD builder source url=https://github.com/redhat-cop/containers-quickstarts.git
        * HTTPD source branch/tag reference.=master
        * HTTPD builder context directory.=s2i-httpd
        * Apache application name=httpd-app
        * HTTPD application source url=https://github.com/sclorg/httpd-container.git
        * HTTPD application source branch/tag reference.=master
        * HTTPD application context directory.=2.4/test/sample-test-app
        * HTTPD application route hostname.=

--> Creating resources with label app=httpd-quickstart-rhel ...
    imagestream "sclorg-httpd-container" created
    imagestream "s2i-httpd" created
    imagestream "httpd-app" created
    buildconfig "s2i-httpd" created
    route "httpd-app" created
    buildconfig "httpd-app" created
    service "httpd-app" created
    deploymentconfig "httpd-app" created
--> Success
    Build scheduled, use 'oc logs -f bc/s2i-httpd' to track its progress.
    Build scheduled, use 'oc logs -f bc/httpd-app' to track its progress.
    Run 'oc status' to view your app.
[esauer@localhost containers-quickstarts]$ oc get pods
[esauer@localhost containers-quickstarts]$ oc get pods
NAME                READY     STATUS    RESTARTS   AGE
s2i-httpd-1-build   0/1       Error     0          18s
[esauer@localhost containers-quickstarts]$ oc logs build/s2i-httpd-1
Cloning "https://github.com/redhat-cop/containers-quickstarts.git" ...
	Commit:	329f59a9788e1deea13ead64003bbc90dfaa7c8d (Merge pull request #8 from sabre1041/s2i-java-bom)
	Author:	Eric Sauer <etsauer@gmail.com>
	Date:	Thu Nov 17 10:52:20 2016 -0500
error: build error: open /tmp/docker-build381466234/s2i-httpd/Dockerfile: no such file or directory
```

**Comment by sabre1041** [comment]
@etsauer you will need to point the buildconfig to my branch. the template is configured for the upstream repo post PR merge

**Comment by etsauer** [comment]
ok, my mistake. lgtm.

**Pull request merged**
