### PR TITLE
added build ci for jenkins agents

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
starts to answer the below in its most basic form - build the containers
- https://github.com/redhat-cop/containers-quickstarts/issues/553

#### How do we test this?
CI runs. this PR isn't to fix any agents that fail.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Review by pabrahamsson — COMMENTED** [review]
As you know we currently also test the images in Jenkins through the `Jenkinsfile.test`. What are your thoughts on accomplishing the same functionality through GH actions? Or do you think a successful image build is enough?
/hold

**Comment by garethahealy** [comment]
@pabrahamsson ; am currently playing around the Jenkinsfile-runner via a github action to see if that'll work to test the agents

**Comment by pabrahamsson** [comment]
Ah, I see your [comment](https://github.com/redhat-cop/containers-quickstarts/issues/553#issuecomment-1041338207) on #553 now

**Review by pabrahamsson — APPROVED** [review]
LGTM

**Pull request merged**
