### PR TITLE
Sonarqube improvements

### PR DESCRIPTION
**Pull request by syvanen**
#### What is this PR About?
This improves the SonarQube by matching the plugin version automatically to upstream SonarQube container image version.
Also adds instructions how to use this quickstart and sets the seed file to point to CoP repo.

#### How do we test this?
Follow instructions now added to README.md

cc: @redhat-cop/containerize-it

### CODE REVIEW

**Comment by syvanen** [comment]
@pabrahamsson or @etsauer  would you have time to review this?

**Comment by sabre1041** [comment]
@syvanen ran through this and deployment was successful. A few things:

1. Correct formatting issues in the _README.md_
2. Provide a set of next steps on how to make use of the container(s) in order to demonstrate the tool in action

**Comment by syvanen** [comment]
@sabre1041 Updated README.md and tried to describe how to take SonarQube into use in the pipeline.

**Comment by sabre1041** [comment]
@syvanen LGTM thanks!

**Pull request merged**
