### PR TITLE
fixed build/publish ci failing

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
fixs: https://github.com/redhat-cop/containers-quickstarts/issues/474

#### How do we test this?
*all* CI should jobs for PR go green

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
CI reports similar to: https://github.com/containers/buildah/issues/1745

**Comment by garethahealy** [comment]
@pabrahamsson ; i have:

1. reverted https://github.com/redhat-cop/containers-quickstarts/pull/473 - was causing syntax issues
2. downgraded all the buildah ci to 18.04, due to above linked issue
3. fixed a few places docker was left over
4. added a path watch to all ci for the github action yaml, so if that changes, ci is re-tested

**Review by pabrahamsson — APPROVED** [review]
/lgtm

**Pull request merged**
