### PR TITLE
Fix a few README URLs

### PR DESCRIPTION
**Pull request by pabrahamsson**
#### What is this PR About?
Update a few links in READMEs

#### How do we test this?
Provide commands/steps to test this PR.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by pabrahamsson** [comment]
This PR is dependent on #536 for CI to pass but could be merged manually (CI will not test these changes).

**Review by springdo — DISMISSED** [review]
/lgtm

**Comment by pabrahamsson** [comment]
@springdo I believe the PR also needs [GitHub's PR review approval](https://github.com/redhat-cop/containers-quickstarts/pull/537/files) (button in top rightish corner) in order to merge.

**Review by springdo — APPROVED** [review]

**Pull request merged**
