### PR TITLE
🦅 ADD - yq for yaml manipulation as part of pipeline 🦅

### PR DESCRIPTION
**Pull request by springdo**
#### What is this PR About?
I want to add `yq` for yaml manipulation to this slave. 
In my pipeline, I'm going to edit the yaml & commit it, then kick ArgoCD. 
I don't want to have to load up a new slave just to do this small manipulation.

#### How do we test this?
1. `docker build -t name/jenkins-slave-argocd .`
2. `docker run --rm -it  --entrypoint=/bin/bash name/jenkins-slave-argocd:latest`
3. Test: expected out put `test.passing == true`
```
cat << EOF | yq w - 'test.passing' true
---
test:
  passing: false
EOF
```

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by springdo** [comment]
🦄 🔥 
/assign @pcarney8

**Comment by garethahealy** [comment]
@springdo ; have you had a look at the other yq? 
- https://pypi.org/project/yq/

Its a wrapper around jq.

**Comment by springdo** [comment]
@garethahealy nope Ive not looked at it. Any good? Want me to swap it out for this one?

**Comment by garethahealy** [comment]
I've found it a lot better as I've been using jq on a weekly basis recently, so its the same syntax - no need to learn something else.

i'd leave it as is for time being, but maybe something to look at in future.

**Pull request merged**
