### PR TITLE
Making all the applier stuff the same and adding in where missing

### PR DESCRIPTION
**Pull request by pcarney8**
#### What is this PR About?
standardizing the applier stuff so that running CI on this repository will be easier

#### How do we test this?
TBD, probably just run the jenkinsfile when it get here.

Related to #157 

cc: @redhat-cop/containerize-it

### CODE REVIEW

**Comment by etsauer** [comment]
@pcarney8 since the goal is to standardize the applier stuff, we should be able to test with this for loop:

```
for dir in $(ls -ld */ | awk '{print $9}'); do 
  pushd $dir && ansible-galaxy install -r requirements.yml -p galaxy -f &&\
  ansible-playbook -i .applier galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml; 
  popd; 
done
```

FYI, i've run this test with what you have so far, and I'm primarily getting one error message over and over:

```
TASK [openshift-applier : Create OpenShift objects based on template with params for 'Environment Setup : Create Projects'] ****************
failed: [localhost] (item={'oc_path': ''}) => {"changed": true, "cmd": "oc process   https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml   --param='NAMESPACE=tool-box' --param='NAMESPACE_DISPLAY_NAME=tool-box'  --ignore-unknown-parameters | oc create  -f - ", "delta": "0:00:00.152858", "end": "2019-01-14 16:37:14.908796", "failed_when_result": true, "msg": "non-zero return code", "oc_param_file_item": {"oc_path": ""}, "rc": 1, "start": "2019-01-14 16:37:14.755938", "stderr": "error: invalid argument \"https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml\"\nerror: no objects passed to create", "stderr_lines": ["error: invalid argument \"https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml\"", "error: no objects passed to create"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/esauer/src/containers-quickstarts/tool-box/galaxy/openshift-applier/playbooks/openshift-cluster-seed.retry
```

**Comment by etsauer** [comment]
@pcarney8 

Hit an issue with one of the inventories:

```
- extracting openshift-applier to /home/esauer/src/containers-quickstarts/gitlab-ce/galaxy/openshift-applier
- openshift-applier (v2.0.6) was installed successfully
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to have been in '/tmp/quickstart/.applier/group_vars/seed-hosts.yml': line 7, column 20, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

app_params:
  LDAP_BIND_DN: uid: john.doe,ou: People,dc: example,dc: com
                   ^ here
```

**Comment by pcarney8** [comment]
updated with double quotes

**Comment by etsauer** [comment]
Found another:

```
TASK [openshift-applier : Apply OpenShift objects based on static files for 'imagestream : rhel7'] ******
Friday 18 January 2019  17:51:50 +0000 (0:00:00.051)       0:00:13.024 ******** 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["oc", "apply", "-n", "rabbitmq", "-f", "/tmp/containers-quickstarts/rabbitmq/.applier/../.openshift/templates/imagestreams/images.yml"], "delta": "0:00:06.186030", "end": "2019-01-18 17:51:56.339730", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2019-01-18 17:51:50.153700", "stderr": "error: unable to recognize \"/tmp/containers-quickstarts/rabbitmq/.applier/../.openshift/templates/imagestreams/images.yml\": no matches for kind \"List\" in version \"vi\"", "stderr_lines": ["error: unable to recognize \"/tmp/containers-quickstarts/rabbitmq/.applier/../.openshift/templates/imagestreams/images.yml\": no matches for kind \"List\" in version \"vi\""], "stdout": "", "stdout_lines": []}

PLAY RECAP **********************************************************************************************
localhost                  : ok=36   changed=2    unreachable=0    failed=1   

```

**Comment by pcarney8** [comment]
@etsauer updated

**Pull request merged**
