### PR TITLE
🐻 ADD - hugo static site builder 🐻

### PR DESCRIPTION
**Pull request by springdo**
#### What is this PR About?
Describe the contents of the PR
Hugo static site stuff

#### How do we test this?
Provide commands/steps to test this PR.
docker build ...  / use the test script

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Review by ckavili — COMMENTED** [review]
thanks Donal 👍  LGTM.

**Comment by springdo** [comment]
/approve

hmmm loooks like tide is stuck. I can try run the approve command too

**Comment by springdo** [comment]
@garethahealy  - any chance you can bump this one?

**Review by pabrahamsson — APPROVED** [review]
/lgtm

**Pull request merged**
