### PR TITLE
jenkins-agent-golang: Use Go 1.15.6, update sonar-scanner version & update test + README

### PR DESCRIPTION
**Pull request by pabrahamsson**
#### What is this PR About?
Bump Go to `1.15.6` for `jenkins-agent-golang` and also update to the latest version of `sonar-scanner-cli`.
Test has been updated with `sonar-scanner -v` and `README` has been updated with instructions for how to build image with custom version of Go.

#### How do we test this?
Clone this repo, then:
```
./_test/setup.sh applier cq_test pabrahamsson/containers-quickstarts jenkins-agent-golang-1.15
./_test/setup.sh test cq_test pabrahamsson/containers-quickstarts jenkins-agent-golang-1.15
```

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Review by garethahealy — APPROVED** [review]

**Comment by pabrahamsson** [comment]
@garethahealy I had to merge upstream after #425 was merged which removed your lgtm, mind adding it back?

**Comment by garethahealy** [comment]
woops, wrong button

/lgtm

**Comment by pabrahamsson** [comment]
Having a field day with Jenkins in the CI env :crying_cat_face:

**Pull request merged**
