### PR TITLE
Updated to handle random UID from OpenShift

### LINKED ISSUE #138: ZAP slave fails to find Username/Home because of random start-up user in OpenShift
Need to allow for the `/etc/passwd` file to be updated on startup so that the randomly chosen UID from OpenShift is integrated into `/etc/passwd`.

### PR DESCRIPTION
**Pull request by InfoSec812**
#### What is this PR About?
Resolves #138 

#### How do we test this?
```
docker build -t test-zap .
docker run -it zap-x.sh -daemon -host 0.0.0.0 -port -8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
```

cc: @redhat-cop/containerize-it

### CODE REVIEW

**Comment by syvanen** [comment]
ping @InfoSec812

**Comment by InfoSec812** [comment]
I had to make a number of changes to get this to work as a Proxy when running Selenium tests through ZAP. I will be updating and re-submitting a PR with all of the changes we adapted over the course of my most recent residency.

**Comment by pabrahamsson** [comment]
@InfoSec812 what is the latest status on this PR?

**Comment by InfoSec812** [comment]
@pabrahamsson I will try to revisit this when I have some free time, but that may be a few weeks.

**Comment by pabrahamsson** [comment]
Thanks @InfoSec812

**Comment by InfoSec812** [comment]
PR #192 supersedes this PR and has further improvements. Closing this PR

**Pull request closed without merging**
