### PR TITLE
Image management jenkins slave

### PR DESCRIPTION
**Pull request by sabre1041**
#### What is this PR About?
Adds a Jenkins slave image to perform image management (promotions using [skopeo](https://github.com/projectatomic/skopeo/))

#### How do we test this?
A template has been provided to automate the building process

Execute the following from within the *jenkins-slaves/templates* folder to instantiate the template to create the requisite imagestreams and buildconfig

```
oc process -v=SOURCE_REPOSITORY_URL=https://github.com/sabre1041/containers-quickstarts.git,SOURCE_REPOSITORY_REF=jenkins-slave-image-mgmt -f jenkins-slave-image-mgmt-template.json | oc create -f-
```

cc: @redhat-cop/containerize-it @etsauer

### CODE REVIEW

**Comment by etsauer** [comment]
@sabre1041 can we put some basic instructions in a readme?

**Comment by etsauer** [comment]
@sabre1041 i've tested the build of the image, and everything seems to build fine, but when I start a pod from the image, the skopeo utility doesn't appear to exist:

```
[esauer@localhost containers-quickstarts]$ oc new-app jenkins-slave-image-mgmt
--> Found image e403db9 (4 minutes old) in image stream jenkins-slave-image-mgmt under tag "latest" for "jenkins-slave-image-mgmt"

    Jenkins Slave Image Management 
    ------------------------------ 
    Image management tools on top of the jenkins slave base image

    Tags: openshift, jenkins, slave, copy

    * This image will be deployed in deployment config "jenkins-slave-image-mgmt"
    * The image does not expose any ports - if you want to load balance or send traffic to this component
      you will need to create a service with 'expose dc/jenkins-slave-image-mgmt --port=[port]' later

--> Creating resources with label app=jenkins-slave-image-mgmt ...
    deploymentconfig "jenkins-slave-image-mgmt" created
--> Success
    Run 'oc status' to view your app.
[esauer@localhost containers-quickstarts]$ oc get pods
NAME                                READY     STATUS             RESTARTS   AGE
jenkins-slave-image-mgmt-1-build    0/1       Completed          0          5m
jenkins-slave-image-mgmt-1-deploy   1/1       Running            0          32s
jenkins-slave-image-mgmt-1-gs1jg    0/1       CrashLoopBackOff   1          29s
[esauer@localhost containers-quickstarts]$ oc rsh jenkins-slave-image-mgmt-1-deploy
sh-4.2$ 
sh-4.2$ 
sh-4.2$ 
sh-4.2$ error: error executing remote command: error executing command in container: Error executing in Docker Container: 137
[esauer@localhost containers-quickstarts]$ skopeo inspect docker://docker.io/fedora
bash: skopeo: command not found...
Install package 'skopeo' to provide command 'skopeo'? [N/y] n
```

**Comment by sabre1041** [comment]
@etsauer it appears that you are attempting to `rsh` into the deploy pod. but your actual execution of `skopeo` is occuring on your local machine

The slave image cannot be run as standalone by default as it expects to be launched from Jenkins and then connect back to the running instance. You can validate `skopeo` is installed by launching a *debug* pod

```
oc debug dc/jenkins-slave-image-mgmt
```

**Comment by etsauer** [comment]
retracted. looks good. just the README

**Comment by sabre1041** [comment]
@etsauer Added README

**Comment by etsauer** [comment]
lgtm.

**Pull request merged**
