### PR TITLE
Enhancement for non-priveleged users. Can specify arbitrary namespace…

### PR DESCRIPTION
**Pull request by etsauer**
… in which to do image builds

#### How do we test this?
```
cicd/pipeline deploy myapp --image-namespace is-namespace
```

cc: @redhat-cop/containerize-it

### CODE REVIEW

**Comment by sabre1041** [comment]
@etsauer 

Received this error during the initial build phase of the pipeline

```
Uploading directory "oc-build" as binary input for the build ...
The ImageStreamTag "jboss-webserver30-tomcat8-openshift:1.2" is invalid: from: Error resolving ImageStreamTag jboss-webserver30-tomcat8-openshift:1.2 in namespace is-namespace: imagestreams "jboss-webserver30-tomcat8-openshift" not found
+ exit 1
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
``` 

Also, noticed small formatting issue in the `pipeline` script

`echo "You must be in the `containers-quickstarts` directory to run this script."`

"containers-quickstarts" is not printed out. Most likely need to replace with single quotes

**Comment by etsauer** [comment]
@sabre1041 yes, the latest commit should fix that pipeline issue.

fixed the error output as well.

**Comment by sabre1041** [comment]
@etsauer Pipeline completes successfully.

Only question I noticed is that there is an `ImageChange` trigger on the `generic-java-jenkins-pipeline`. This will cause a build that will never contain a source as it need to be triggered manually. Would recommend removing this trigger. Might need to add a feature enhancement to have jenkins monitor for ImageStream changes to trigger the pipeline

**Comment by etsauer** [comment]
@sabre1041 done.

**Comment by sabre1041** [comment]
lgtm

**Pull request merged**
