### PR TITLE
refactor dockerfile & update Jenkins base to 4.5

### PR DESCRIPTION
**Pull request by usrbinkat**
Improvements:
  - Update jenkins base image from 4.4 > 4.5 (prep for move from ubi7 to ubi8)
  - Reformat Dockerfile for ease of troubleshooting / testing
  - Remove user-interactive build breaking cmd
  - Flip ansible version from env to arg
  - Variablize yum install flags
  - Variablize Pip & yum package instal lists
  - Enable BASH_XTRACEFD for improved build pipeline debugging

Build as usual to test.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by usrbinkat** [comment]
#407 aligns with base image 4.4 > 4.5 version update

**Comment by garethahealy** [comment]
flake related to jenkins-agent-mongodb-pipeline-1, not this PR

/test cq-jenkins-agents-pr-build

**Review by pabrahamsson — APPROVED** [review]
Thank you @usrbinkat, much appreciated
/approve
/lgtm

**Pull request merged**
